# Generated by Django 2.0.7 on 2018-08-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField(auto_now_add=True)),
                ('playerX', models.CharField(max_length=100)),
                ('playerO', models.CharField(max_length=100)),
                ('result', models.IntegerField(choices=[(-1, 'X won'), (0, 'Tie'), (1, 'O won')])),
            ],
        ),
    ]
