# Generated by Django 2.0.7 on 2018-10-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='language',
            field=models.CharField(choices=[('python', 'python'), ('java', 'java')], default='python', max_length=100),
        ),
    ]
